-
  name: this is a simple html project
  hosts: servers
  become: yes
  tasks: 
    - name: Install ngnix
      apt: 
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started

    - name: Deploy webpage
      copy:
        src: index.html
        dest: /var/www/html
